### Create User
POST  http://localhost:3000/user
Content-Type: application/json

{
        "username": "wsau111",
        "password": "password"
}
    
### Update User
PUT http://localhost:3000/user/9
Content-Type: application/json

{
    "username": "wassss",
    "password": "newpassword"
}

### Delete User
DELETE http://localhost:3000/user/6

### Search User
GET http://localhost:3000/user/search?q=d
Content-Type: application/json